### ISSUE TITLE
Fail fast with invalid arguments

### ISSUE THREAD

**Issue by jarcec** [clusterdock/topology_cdh#13]
In one of my runs I've specified both --include-services and --exclude-services which eventually ended up with:

```
Traceback (most recent call last):
  File "/usr/local/bin/clusterdock", line 9, in <module>
    load_entry_point('clusterdock==1.3.2', 'console_scripts', 'clusterdock')()
  File "/usr/local/lib/python3.5/dist-packages/clusterdock/cli.py", line 175, in main
    action.main(args)
  File "/home/ubuntu/topology_cdh/start.py", line 268, in main
    raise ValueError('Cannot pass both --include-services and --exclude-services.')
ValueError: Cannot pass both --include-services and --exclude-services.
```

I was somehow expecting that it will fail but wanted to try it anyway. The interesting bit is that the code run for 6 minutes. What about validating the arguments at the begging of execution to give the user immediate feedback?

**Comment by dimaspivak** [comment]
Patches welcome! :)
